version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - default
# Uncomment the following lines to enable persistent storage for the database
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./config/config.json:/app/config/config.json
    depends_on:
      - postgres
    networks:
      - default
